name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type:feature", "status:ready", "priority:P2"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your idea.
  
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief feature description
      placeholder: What feature do you want?
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Complete description of the feature
      placeholder: Explain the feature in detail
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Why do we need this?
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: Describe the ideal solution
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, diagrams, or other relevant information
